name: Deploy NestJS to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Actualizar código en EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu/proyects/vffac/backend-nestjs
            
            echo "→ Trayendo los últimos cambios de Git..."
            git fetch --all
            git reset --hard origin/main
            
            echo "→ Contenido actual de la carpeta:"
            ls -la
            
            echo "✅ Código actualizado. Listo para tus pruebas."